### PR TITLE
port to Minecraft 1.12.1

### PR DESCRIPTION
**Pull request by asiekierka**
The effect jar seems to lack a model, but the rest seems to work fine!

### CODE REVIEW

**Comment by mezz** [comment]
Can you target the new 1.12 branch? https://github.com/ForestryMC/MagicBees/tree/1.12

**Comment by asiekierka** [comment]
@mezz Isn't it easier for you to redirect it via Git commands? If not, sure

**Comment by mezz** [comment]
I didn't try because I'm pretty sure it will conflict with the changes on that branch.

**Comment by Elec332** [comment]
I have quite a few unsynced changes on 1.12 that I cant push because I have
no internet here, Ill be home by monday, and try to merge it then.

Sorry, but I didnt know that this port existed

Op 17 aug. 2017 08:28 schreef "mezz" <notifications@github.com>:

I didn't try because I'm pretty sure it will conflict with the changes on
that branch.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/ForestryMC/MagicBees/pull/31#issuecomment-322980836>,
or mute the thread

**Comment by Elec332** [comment]
There are too many conflicts unfortunately, but I think almost everything in your pull has now been implemented. Please correct me if im wrong ;)

Im sorry I couldn't merge your pull.

**Comment by asiekierka** [comment]
It's alright, don't worry!

Also, the pull was really a straight port.

**Pull request closed without merging**
